### PR TITLE
Replace Qt with PIL

### PR DESCRIPTION
**Pull request by anarsoul**
Using Qt just for parsing PNG and resizing images is overkill. PIL is a much lighter alternative, so use PIL instead

### CODE REVIEW

**Comment by Molodos** [comment]
That might be more lightweight, but also this is more or less a fork of the Cura plugin version (Cura comes with Qt and the UIs of the plugin are also made with Qt). So in order to make it easier to transfer new features from the Cura plugin to this one, it is generally easier to stay with Qt.
Did you have any performance issues or why did you rewrite it exactly?

**Comment by anarsoul** [comment]
> That might be more lightweight, but also this is more or less a fork of the Cura plugin version (Cura comes with Qt and the UIs of the plugin are also made with Qt). So in order to make it easier to transfer new features from the Cura plugin to this one, it is generally easier to stay with Qt. Did you have any performance issues or why did you rewrite it exactly?

It may be OK for Cura, since it is written in Python and uses Qt, but Orca (or Prusa) Slicer are not using Qt. Pulling a huge library where a native PIL would do is not a good idea.

Moreover having smaller dependencies will make packaging easier and packages smaller. Notice that your Windows binary is over 27M.

I don't think that switching to PIL will make porting code/features from original plugin harder, just take a look at the code, the changes are pretty trivial.

**Comment by Molodos** [comment]
As long as it doesn't change the performance too much, the only point is the binary size. I will have a look at it later.

**Comment by anarsoul** [comment]
> If you could do those changes, I will merge. (I can also do them myself instead of merging if you want, but it would take longer as I do not have much time at the moment) :D

I'll look into it over the weekend

**Comment by anarsoul** [comment]
I found https://github.com/VBitsHub/elegoo_moonraker which fixes the issue from the printer's side (and it also fixes parsing printing time estimates), so I'm not planning to work on it anymore

**Pull request closed without merging**
